port: 8080
admin:
  name: 'Adminovich'
  username: 'Admin'
  password: 'passwordForAdmin'
db:
  username: 'postgres'
  password: 'qwerty'
  host: 'localhost'
  port: '5436'
  dbname: 'postgres'
  sslmode: 'disable'
